sonar.projectKey=PEI-HAZARDS_IntelligentLogistics
sonar.organization=pei-hazards
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/*.test.py,**/tests/**,**/htmlcov/**,**/__pycache__/**,src/AI_APP/broker/dashboard/**,deprecated/**,src/shared/src/kafka_simulate.py
# Exclude agents from duplication detection only
sonar.cpd.exclusions=**/init.py,**/setup.py
sonar.python.version=3.14
sonar.python.coverage.reportPaths=coverage.xml
sonar.coverage.exclusions=**/__main__.py,**/__init__.py,**/setup.py,**/init.py,**/config.py,src/V_APP/Data_Module/**,src/V_APP/api_gateway/**,src/V_APP/keycloak/**,src/V_APP/test_scripts/**,src/V_APP/api_gateway/src/main.py,src/shared/src/base_gateway.py,src/AI_APP/broker/dashboard/**,src/devops/**,src/streaming_middleware/**,src/streamV2/**,src/go2rtc/**,**/tests/**,src/V_APP/Data_Module/scripts/**
