sonar.projectKey=PEI-HAZARDS_IntelligentLogistics
sonar.organization=pei-hazards
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/*.test.py,**/tests/**,**/htmlcov/**,**/__pycache__/**
# Exclude agents from duplication detection only
sonar.cpd.exclusions=**/init.py,**/setup.py
sonar.python.version=3.14
sonar.python.coverage.reportPaths=coverage.xml
sonar.coverage.exclusions=**/__main__.py,**/__init__.py,**/setup.py,**/init.py,src/V_APP/Data_Module/**,src/V_APP/api_gateway/**,src/AI_APP/broker/dashboard/**,src/devops/**,src/streaming_middleware/**,src/streamV2/**,src/go2rtc/**,**/tests/**
