"""
Test A1 — Verify that arrival_id is NOT generated by ORM event listener.

The arrival_id must be generated exclusively by the PostgreSQL trigger
``trg_generate_arrival_id`` (using ``appointment_arrival_seq`` sequence),
which is concurrency-safe.  The previous ORM ``before_insert`` listener
used ``max(arrival_id)+1`` which was race-prone under concurrent inserts.

This test ensures no ORM-level listener silently re-introduces the
race condition.
"""

import pytest
from sqlalchemy import event as sa_event, inspect as sa_inspect

from infrastructure.persistence.sql_models import Appointment


def _dummy_before_insert(mapper, connection, target):
    """Sentinel function used only to probe event registration."""
    pass


@pytest.mark.unit
class TestArrivalIdNoORMListener:
    """arrival_id generation must be delegated to PostgreSQL trigger only."""

    def test_no_before_insert_listener_for_arrival_id(self):
        """Appointment model must NOT have a before_insert event listener."""
        # sa_event.contains checks if a *specific* fn is registered.
        # If the old generate_arrival_id were still attached, we could
        # not reference it by name (it was removed).  Instead, we inspect
        # the mapper dispatch to verify there are zero listeners.
        mapper = sa_inspect(Appointment)
        dispatch = mapper.dispatch
        # In SQLAlchemy 2.x, dispatch.before_insert is a _ClsLevelDispatch.
        # Iterating it yields registered listener callables.
        listeners = list(dispatch.before_insert)
        assert len(listeners) == 0, (
            f"Appointment has {len(listeners)} 'before_insert' event listener(s). "
            "arrival_id generation must use only the SQL trigger "
            "(trg_generate_arrival_id) to avoid race conditions."
        )

    def test_appointment_created_without_arrival_id_stays_none(self):
        """
        When creating an Appointment ORM instance without arrival_id,
        the attribute must remain None — the DB trigger will fill it.
        """
        appt = Appointment(
            booking_reference="BK-TEST-001",
            driver_license="PT99999999",
            truck_license_plate="AA-00-AA",
            terminal_id=1,
            status="in_transit",
        )
        assert appt.arrival_id is None, (
            "arrival_id should be None at ORM level; "
            "the SQL trigger generates it on INSERT."
        )

    def test_appointment_with_explicit_arrival_id_is_preserved(self):
        """
        If a caller explicitly provides arrival_id, it must be preserved
        (the SQL trigger only fills it when NULL/empty).
        """
        appt = Appointment(
            arrival_id="PRT-9999",
            booking_reference="BK-TEST-002",
            driver_license="PT99999999",
            truck_license_plate="AA-00-AA",
            terminal_id=1,
            status="in_transit",
        )
        assert appt.arrival_id == "PRT-9999"
