class MyClass(BaseClass):

    # 1. Class variables / class-level constants
    MAX_RETRIES = 3
    _instance_count = 0

    # 2. __init__
    def __init__(self, param):
        self.param = param
        self._internal_state = None

    # 3. __post_init__ (if dataclass)

    # 4. Other dunder/magic methods
    def __repr__(self): ...
    def __str__(self): ...
    def __len__(self): ...
    def __eq__(self, other): ...

    # 5. Class methods
    @classmethod
    def from_dict(cls, data): ...

    # 6. Static methods
    @staticmethod
    def validate_input(value): ...

    # 7. Properties
    @property
    def status(self): ...

    @status.setter
    def status(self, value): ...

    # 8. Public methods (the main interface of the class)
    def start(self): ...
    def stop(self): ...
    def process(self, data): ...

    # 9. Protected methods (single underscore — internal but overridable)
    def _prepare(self): ...
    def _validate(self): ...

    # 10. Private methods (double underscore — not meant to be overridden)
    def __parse_frame(self): ...
    def __cleanup(self): ...